pagopa/idpay-payment-instrument

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/resources/application.yml

change cron from 5 minutes to 2 hours

chore: change cron scheduler

---

src/main/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceImpl.java

**Description**
The purpose of this PR is to allign performance logs for the initiative delete.
**List of changes**
-  Modify performance log and info log
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

fix: delete initiative performance log fix

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/anchore.yml

* fix slack notification step condition
* typo

chore: promotion to uat

---

Dockerfile

fix: IDP-1760 fix new critical CVE-2022-48174 (#133)

---

pom.xml
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

chore: Bump POM version

---

pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/utils/MemoryAppender.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
src/test/java/it/gov/pagopa/payment/instrument/utils/AuditUtilitiesTest.java

feat: Release dev

---

src/main/java/it/gov/pagopa/payment/instrument/dto/QueueCommandOperationDTO.java
src/main/java/it/gov/pagopa/payment/instrument/model/PaymentInstrument.java
src/main/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentRepository.java
src/main/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentRepositoryExtended.java
src/main/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentRepositoryExtendedImpl.java
src/main/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentRepositoryExtendedImplTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceTest.java

The purpose of this pr is to change the method of deletion from the database from a bulk delete to a paged delete.
- Modified QueueCommandOperationDTO
- Created extended repository interface and implementation and added paged delete method
- Modified JUnit tests

fix: IDP 1828 idpay payment instrument

---

src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentDiscountServiceTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceTest.java

- fix unit test
- added controll of type of initiative on idpayCode enrollemnt

fix: unit test

---

.devops/deploy-pipelines.yml

fix: revert last mod

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
src/main/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceTest.java

The purpose of this PR is to fix delete initiative in wallet microservice. [1813](https://pagopa.atlassian.net/jira/software/c/projects/IDP/boards/349?modal=detail&selectedIssue=IDP-1813)
- modify queue command operation DTO
- modify env variables

fix: [IDP-1828] fix delete initiative

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
src/main/java/it/gov/pagopa/payment/instrument/controller/PaymentInstrumentControllerImpl.java
src/main/java/it/gov/pagopa/payment/instrument/dto/CheckEnrollmentDTO.java
src/main/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceImpl.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentDiscountServiceTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceTest.java

This PR includes:
- [IDP-1828](https://github.com/pagopa/idpay-payment-instrument/pull/149)
[IDP-1828]: https://pagopa.atlassian.net/browse/IDP-1828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Promote to UAT

---

src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
src/main/java/it/gov/pagopa/payment/instrument/utils/Utilities.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceTest.java
src/test/java/it/gov/pagopa/payment/instrument/utils/UtilitiesTest.java

fix-response-from-wallet

---

src/main/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceTest.java

Fix control delete qrCode
It's not possible to delete an instrument of QRCODE type

feat: PROMOTION UAT

---

pom.xml
src/main/java/it/gov/pagopa/payment/instrument/model/PaymentInstrumentCode.java
src/main/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentCodeRepositoryExt.java
src/main/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentCodeRepositoryExtImpl.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/EncryptCodeService.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/EncryptCodeServiceImpl.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentCodeRepositoryExtTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/EncryptCodeServiceTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceTest.java

- Creation PinBlock
- Hash PinBlock

feat: IDP-1766-crittografare-il-pin-della-cie

---

.grype.yaml
pom.xml
src/main/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtils.java
src/test/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtilsTest.java
src/test/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtilsTestIntegrated.java

feat: IDP-1935 KeyVaultPOC

---

src/main/java/it/gov/pagopa/payment/instrument/config/AzureConfig.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionService.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceTest.java

fix: test unit verifica idpayCode

---

src/main/java/it/gov/pagopa/payment/instrument/model/PaymentInstrumentCode.java
src/main/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentCodeRepository.java
src/main/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentCodeRepositoryExt.java
src/main/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentCodeRepositoryExtImpl.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionService.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceImpl.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/repository/PaymentInstrumentCodeRepositoryExtTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceTest.java

Change **_id** in the collection _payment_instrument_code_ with the field **userId**

fix: IDP-1977-cambiare-id-nella-collezione-payment-instrument-code

---

src/main/java/it/gov/pagopa/payment/instrument/constants/PaymentInstrumentConstants.java
src/main/java/it/gov/pagopa/payment/instrument/dto/mapper/InstrumentFromDiscountDTO2PaymentInstrumentMapper.java
src/main/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/dto/mapper/InstrumentFromDiscountDTO2PaymentInstrumentMapperTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceTest.java

Replace into PaymentInstrumentConstants the QRCODE costant with new APP_IO_PAYMENT

fix: handle BARCODE/QRCODE instrumentType

---

.grype.yaml
Dockerfile
pom.xml
src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/stream/StreamsHealthIndicatorTest.java

fix: Idp 2016 fix CVE

---

src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceImpl.java

fix: Promote UAT

---

postman/idpay-payment-instrument-e2e.postman_collection.json

chore: fix postman test

---

postman/idpay-payment-instrument-e2e.postman_collection.json

chore: fix postman test (#174)

---

.grype.yaml
Dockerfile
pom.xml
src/test/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtilsTestIntegrated.java

fix: IDP-2196 fix Cve (#187)

---

src/main/java/it/gov/pagopa/payment/instrument/controller/PaymentInstrumentControllerImpl.java
src/main/java/it/gov/pagopa/payment/instrument/dto/DeactivationBodyDTO.java
src/main/java/it/gov/pagopa/payment/instrument/dto/UnsubscribeBodyDTO.java
src/main/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentService.java
src/main/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceImpl.java
src/test/java/it/gov/pagopa/payment/instrument/controller/PaymentInstrumentControllerTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/PaymentInstrumentServiceTest.java

[IDP-2345](https://pagopa.atlassian.net/browse/IDP-2345)
- Added "channel" as field of DTO in disable instrument api
To be able to set the channel correctly based on who is calling these api
[IDP-2345]: https://pagopa.atlassian.net/browse/IDP-2345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-2345] added channel field in disable instrument DTO

---

src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceImpl.java

[IDP-2356](https://pagopa.atlassian.net/browse/IDP-2356)
Edited code data pinblock
[IDP-2356]: https://pagopa.atlassian.net/browse/IDP-2356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-2356] edited code data pinblock

---

src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceImpl.java
src/test/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtilsTest.java
src/test/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtilsTestIntegrated.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceTest.java

Task [IDP-2371](https://pagopa.atlassian.net/browse/IDP-2371)
- changed algorithm from RSA-OAEP to RSA-OAEP-256
[IDP-2371]: https://pagopa.atlassian.net/browse/IDP-2371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IDP-2371] fix RSA-OAEP algorithm

---

src/main/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtils.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionService.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceImpl.java
src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
src/test/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtilsTest.java
src/test/java/it/gov/pagopa/common/azure/keyvault/AzureEncryptUtilsTestIntegrated.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/IdpayCodeEncryptionServiceTest.java
src/test/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceTest.java

fix: [IDP-2371] fix decrypt and encrypt pinblock

---

specs/asyncapi.yml

chore: [IDP-2481] add async yml

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
pom.xml
specs/asyncapi.yml

- Fix CVE [PR](https://github.com/pagopa/idpay-payment-instrument/pull/208)

chore: promote to MAIN
